"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
// HodReviewModal.tsx — pure UI component, receives all state via props
var react_1 = tslib_1.__importDefault(require("react"));
var Hodreviewmodal_module_scss_1 = tslib_1.__importDefault(require("./Hodreviewmodal.module.scss"));
var RATING_LABELS = {
    1: { label: "1 - NOT ACCEPTABLE", color: "#ef4444" },
    2: { label: "2 - ACCEPTABLE", color: "#3b82f6" },
    3: { label: "3 - EXCELLENT", color: "#22c55e" },
};
var HodReviewModal = function (_a) {
    var _b;
    var open = _a.open, candidate = _a.candidate, decision = _a.decision, comments = _a.comments, commentsError = _a.commentsError, decisionError = _a.decisionError, submitting = _a.submitting, alertMsg = _a.alertMsg, alertType = _a.alertType, onSetDecision = _a.onSetDecision, onSetComments = _a.onSetComments, onSubmit = _a.onSubmit, onCancel = _a.onCancel, onHideAlert = _a.onHideAlert;
    if (!open || !candidate)
        return null;
    var c = candidate;
    return (react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.overlay },
        react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.modal },
            alertMsg && (react_1.default.createElement("div", { className: [Hodreviewmodal_module_scss_1.default.alert, alertType === "error" ? Hodreviewmodal_module_scss_1.default.alertErr : Hodreviewmodal_module_scss_1.default.alertOk].join(" ") },
                react_1.default.createElement("span", null, alertMsg),
                react_1.default.createElement("button", { onClick: onHideAlert }, "\u2715"))),
            react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.header },
                react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.headerLeft },
                    react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.avatar },
                        react_1.default.createElement("svg", { width: "20", height: "20", viewBox: "0 0 24 24", fill: "none", stroke: "#1a73e8", strokeWidth: "2" },
                            react_1.default.createElement("path", { d: "M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" }),
                            react_1.default.createElement("circle", { cx: "12", cy: "7", r: "4" }))),
                    react_1.default.createElement("div", null,
                        react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.breadcrumb },
                            react_1.default.createElement("span", null, "CANDIDATE SELECTION"),
                            react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.bChev }, "\u203A"),
                            react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.bActive }, "EVALUATION PREVIEW")),
                        react_1.default.createElement("h1", { className: Hodreviewmodal_module_scss_1.default.title }, "Candidate Evaluation Review"),
                        react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.jobRow },
                            react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.jobCode }, c.jobCode),
                            react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.jobDot }, "\u2022"),
                            react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.jobPos }, c.positionTitle)))),
                react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.headerRight },
                    react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.gpaBox },
                        react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.gpaLabel }, "OVERALL GPA"),
                        react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.gpaVal }, c.gpa)),
                    react_1.default.createElement("button", { className: Hodreviewmodal_module_scss_1.default.closeBtn, onClick: onCancel }, "\u2715"))),
            react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.body },
                react_1.default.createElement("aside", { className: Hodreviewmodal_module_scss_1.default.leftPanel },
                    react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.panelScroll },
                        react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.candidateNameSection },
                            react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.candidateName }, c.applicantName),
                            react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.nationalityTag }, (_b = c.nationality) === null || _b === void 0 ? void 0 : _b.toUpperCase())),
                        react_1.default.createElement(IF, { label: "GENDER", value: c.gender, icon: "\uD83D\uDC64" }),
                        react_1.default.createElement(IF, { label: "QUALIFICATION", value: c.qualification, icon: "\uD83D\uDCC4" }),
                        react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.twoCol },
                            react_1.default.createElement(IF, { label: "MINING EXP.", value: c.miningExp, icon: "\uD83D\uDCC8" }),
                            react_1.default.createElement(IF, { label: "RELATED EXP.", value: c.relatedExp, icon: "\uD83D\uDCC8" })),
                        react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.twoCol },
                            react_1.default.createElement(IF, { label: "INTERVIEW DATE", value: c.interviewDate, icon: "\uD83D\uDCC5" }),
                            react_1.default.createElement(IF, { label: "LEVELS", value: c.interviewLevel, icon: "\uD83D\uDD32" })),
                        react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.twoCol },
                            react_1.default.createElement(IF, { label: "CONFLICTS", value: c.conflicts, icon: "\u26A0\uFE0F" }),
                            react_1.default.createElement(IF, { label: "DISABILITY", value: c.disability, icon: "\u267F" })),
                        c.panelMembers.length > 0 && (react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.panelSection },
                            react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.panelLabel },
                                react_1.default.createElement("svg", { width: "13", height: "13", viewBox: "0 0 24 24", fill: "none", stroke: "#1a73e8", strokeWidth: "2" },
                                    react_1.default.createElement("path", { d: "M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" }),
                                    react_1.default.createElement("circle", { cx: "9", cy: "7", r: "4" }),
                                    react_1.default.createElement("path", { d: "M23 21v-2a4 4 0 0 0-3-3.87" }),
                                    react_1.default.createElement("path", { d: "M16 3.13a4 4 0 0 1 0 7.75" })),
                                react_1.default.createElement("span", null, "INTERVIEW PANEL")),
                            c.panelMembers.map(function (name, i) { return (react_1.default.createElement("div", { key: i, className: Hodreviewmodal_module_scss_1.default.panelMember },
                                react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.panelNum }, i + 1),
                                react_1.default.createElement("span", null, name))); }))))),
                react_1.default.createElement("main", { className: Hodreviewmodal_module_scss_1.default.rightPanel },
                    react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.panelScroll },
                        c.questions.length > 0 && (react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.section },
                            react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.sectionTitle },
                                react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.sectionAccentOrange }),
                                react_1.default.createElement("div", null,
                                    react_1.default.createElement("h2", { className: Hodreviewmodal_module_scss_1.default.sectionH2 }, "INTERVIEW QUESTIONNAIRES"),
                                    react_1.default.createElement("p", { className: Hodreviewmodal_module_scss_1.default.sectionSub }, "Panel Assessment Results"))),
                            c.questions.map(function (q, idx) {
                                var _a, _b;
                                var rInfo = (_a = RATING_LABELS[q.rating]) !== null && _a !== void 0 ? _a : { label: "".concat(q.rating), color: "#9ca3af" };
                                return (react_1.default.createElement("div", { key: (_b = q.id) !== null && _b !== void 0 ? _b : idx, className: Hodreviewmodal_module_scss_1.default.qCard },
                                    react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.qTop },
                                        react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.qBadge },
                                            "Q",
                                            idx + 1),
                                        react_1.default.createElement("p", { className: Hodreviewmodal_module_scss_1.default.qText }, q.question)),
                                    react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.qBottom },
                                        react_1.default.createElement("div", null,
                                            react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.ratingLabel }, "RATING:"),
                                            react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.ratingBadge, style: { background: rInfo.color + "20", color: rInfo.color, border: "1px solid ".concat(rInfo.color, "40") } }, rInfo.label)),
                                        react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.scoreDisplay },
                                            react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.scoreNum },
                                                q.rating,
                                                react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.scoreMax }, "/3"))))));
                            }))),
                        c.scorecardScores.length > 0 && (react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.section },
                            react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.sectionTitle },
                                react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.sectionAccentGreen }),
                                react_1.default.createElement("div", null,
                                    react_1.default.createElement("h2", { className: Hodreviewmodal_module_scss_1.default.sectionH2 }, "SCORECARD DETAILS"),
                                    react_1.default.createElement("p", { className: Hodreviewmodal_module_scss_1.default.sectionSub }, "Core Competency Assessment (1-5 Scale)"))),
                            react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.scorecardGrid }, c.scorecardScores.map(function (s) { return (react_1.default.createElement("div", { key: s.label, className: Hodreviewmodal_module_scss_1.default.scoreItem },
                                react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.scoreItemHeader },
                                    react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.scoreItemLabel }, s.label),
                                    react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.scoreItemVal },
                                        s.score,
                                        "/",
                                        s.max)),
                                react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.progressBar },
                                    react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.progressFill, style: { width: "".concat((s.score / s.max) * 100, "%") } })))); })),
                            (c.panelRecommendation || c.overallFeedback) && (react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.recRow },
                                c.panelRecommendation && (react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.recLeft },
                                    react_1.default.createElement("p", { className: Hodreviewmodal_module_scss_1.default.recLabel }, "PANEL RECOMMENDATION"),
                                    react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.recTag },
                                        react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.recCheck }, "\u2705"),
                                        react_1.default.createElement("span", null, c.panelRecommendation)))),
                                c.overallFeedback && (react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.recRight },
                                    react_1.default.createElement("p", { className: Hodreviewmodal_module_scss_1.default.recLabel }, "OVERALL EVALUATION FEEDBACK"),
                                    react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.feedbackBox },
                                        "\"",
                                        c.overallFeedback,
                                        "\""))))))),
                        react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.section },
                            react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.decHeader },
                                react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.lightning }, "\u26A1"),
                                react_1.default.createElement("div", null,
                                    react_1.default.createElement("h2", { className: Hodreviewmodal_module_scss_1.default.decTitle }, "Do you wish to select this candidate?"),
                                    react_1.default.createElement("p", { className: Hodreviewmodal_module_scss_1.default.decSub }, "As HOD, please review the evaluation above and provide your final decision."))),
                            react_1.default.createElement("div", { className: [Hodreviewmodal_module_scss_1.default.decGrid, decisionError ? Hodreviewmodal_module_scss_1.default.decGridErr : ""].filter(Boolean).join(" ") },
                                react_1.default.createElement(DecCard, { variant: "select", label: "YES, SELECT", active: decision === "select", onClick: function () { return onSetDecision("select"); } },
                                    react_1.default.createElement("svg", { width: "34", height: "34", viewBox: "0 0 24 24", fill: "none", stroke: "#22c55e", strokeWidth: "2.2", strokeLinecap: "round" },
                                        react_1.default.createElement("circle", { cx: "12", cy: "12", r: "10" }),
                                        react_1.default.createElement("polyline", { points: "9 12 11 14 15 10" }))),
                                react_1.default.createElement(DecCard, { variant: "reject", label: "NO, REJECT", active: decision === "reject", onClick: function () { return onSetDecision("reject"); } },
                                    react_1.default.createElement("svg", { width: "34", height: "34", viewBox: "0 0 24 24", fill: "none", stroke: "#ef4444", strokeWidth: "2.2", strokeLinecap: "round" },
                                        react_1.default.createElement("circle", { cx: "12", cy: "12", r: "10" }),
                                        react_1.default.createElement("line", { x1: "15", y1: "9", x2: "9", y2: "15" }),
                                        react_1.default.createElement("line", { x1: "9", y1: "9", x2: "15", y2: "15" }))),
                                react_1.default.createElement(DecCard, { variant: "hold", label: "ON HOLD", active: decision === "hold", onClick: function () { return onSetDecision("hold"); } },
                                    react_1.default.createElement("svg", { width: "34", height: "34", viewBox: "0 0 24 24", fill: "none", stroke: "#f59e0b", strokeWidth: "2.2", strokeLinecap: "round" },
                                        react_1.default.createElement("polyline", { points: "22 12 18 12 15 21 9 3 6 12 2 12" })))),
                            decisionError && react_1.default.createElement("p", { className: Hodreviewmodal_module_scss_1.default.errMsg }, "Please select a decision."),
                            react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.commentsWrap },
                                react_1.default.createElement("label", { className: [Hodreviewmodal_module_scss_1.default.commentsLabel, commentsError ? Hodreviewmodal_module_scss_1.default.commentsLabelErr : ""].filter(Boolean).join(" ") },
                                    "HOD DECISION JUSTIFICATION / COMMENTS ",
                                    react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.req }, "*"),
                                    commentsError && react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.errInline }, " \u2014 Required")),
                                react_1.default.createElement("textarea", { className: [Hodreviewmodal_module_scss_1.default.commentsArea, commentsError ? Hodreviewmodal_module_scss_1.default.commentsAreaErr : ""].filter(Boolean).join(" "), rows: 4, placeholder: "Provide your final decision rationale\u2026", value: comments, onChange: function (e) { return onSetComments(e.target.value); } })))))),
            react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.footer },
                react_1.default.createElement("button", { className: Hodreviewmodal_module_scss_1.default.cancelBtn, onClick: onCancel, disabled: submitting }, "CANCEL"),
                react_1.default.createElement("button", { className: [Hodreviewmodal_module_scss_1.default.submitBtn, !decision ? Hodreviewmodal_module_scss_1.default.submitOff : ""].filter(Boolean).join(" "), onClick: onSubmit, disabled: submitting || !decision }, submitting ? react_1.default.createElement(react_1.default.Fragment, null,
                    react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.btnSpinner }),
                    " SUBMITTING\u2026") : react_1.default.createElement(react_1.default.Fragment, null,
                    react_1.default.createElement("svg", { width: "15", height: "15", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2.5", strokeLinecap: "round" },
                        react_1.default.createElement("circle", { cx: "12", cy: "12", r: "10" }),
                        react_1.default.createElement("polyline", { points: "9 12 11 14 15 10" })),
                    "SUBMIT ACTION"))))));
};
var IF = function (_a) {
    var label = _a.label, value = _a.value, icon = _a.icon;
    return (react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.infoField },
        react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.infoLabel },
            icon && react_1.default.createElement("span", null, icon),
            " ",
            label),
        react_1.default.createElement("div", { className: Hodreviewmodal_module_scss_1.default.infoValue }, value || "—")));
};
var DecCard = function (_a) {
    var variant = _a.variant, label = _a.label, active = _a.active, onClick = _a.onClick, children = _a.children;
    return (react_1.default.createElement("button", { type: "button", className: [Hodreviewmodal_module_scss_1.default.decCard, Hodreviewmodal_module_scss_1.default["decCard_".concat(variant)], active ? Hodreviewmodal_module_scss_1.default["decCard_".concat(variant, "_on")] : ""].filter(Boolean).join(" "), onClick: onClick },
        react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.decCardIcon }, children),
        react_1.default.createElement("span", { className: Hodreviewmodal_module_scss_1.default.decCardLabel }, label)));
};
exports.default = HodReviewModal;
//# sourceMappingURL=Hodreviewmodal.js.map