"use strict";
// ─── ScorecardConfig.ts ────────────────────────────────────────────────────────
// Local constants / config for the Review Scorecard feature.
Object.defineProperty(exports, "__esModule", { value: true });
exports.HRMSAlertOptions = exports.RecuritmentHRMsg = exports.TabName = exports.RoleName = exports.workflowStatusApi = exports.PositionStatus = exports.WorkflowAction = exports.OVERALL_CRITERIA = exports.CANDIDATE_LIST_COLUMNS = exports.SCORECARD_ROUTES = void 0;
exports.SCORECARD_ROUTES = {
    JobList: "/RecurimentProcess",
    CandidateList: "/RecurimentProcess/HodScoreCard/CandidateList",
    HodViewScorecard: "/RecurimentProcess/HodViewScorecard",
    ReviewProfileList: "/ReviewProfileList",
    InterviewPanelList: "/InterviewPanelList",
};
/** Column definitions for the Candidate List data table */
exports.CANDIDATE_LIST_COLUMNS = [
    { field: "Checkbox", header: "", sortable: false },
    { field: "SNO", header: "S.NO", sortable: true },
    { field: "FullName", header: "Applicant Name", sortable: true },
    { field: "PositionTitle", header: "Position Title", sortable: true },
    { field: "InterviewLevel", header: "Interview Levels", sortable: true },
    { field: "Grade", header: "Grade", sortable: true },
    { field: "GPA", header: "GPA", sortable: true },
    { field: "Status", header: "Status", sortable: false },
    { field: "Action", header: "Action", sortable: false },
];
/** Overall evaluation criteria fields mapped to display labels */
exports.OVERALL_CRITERIA = [
    { field: "RelevantQualification", label: "Qualification (Relevant)" },
    { field: "ReleventExperience", label: "Experience (Relevant)" },
    { field: "Knowledge", label: "Knowledge" },
    { field: "EnergyLevel", label: "Energy Level" },
    { field: "MeetJobRequirement", label: "Meets All Job Requirements" },
    { field: "ContributeTowardsCultureRequried", label: "Will Contribute to the Culture Required" },
    { field: "Experience", label: "Experience" },
    { field: "OtherCriteriaScore", label: "Other Criteria Recognized by Panel" },
    { field: "ConsiderForEmployment", label: "To Consider for Employment (Yes/No)" },
];
exports.WorkflowAction = {
    Approved: 1,
    Reject: 2,
    Revert: 3,
    Transfer: 4,
    Submitted: 5,
    Closed: 6,
    ReSubmitted: 7,
    OnHold: 10,
    Decline: 12
};
exports.PositionStatus = {
    Vacant: "Vacant",
    RecruitmentInitiator: "Recruitment Initiator",
    Filled: "Filled",
    RecruitmentInProgress: "Recruitment InProgress"
};
exports.workflowStatusApi = {
    HRPending: "WS01",
    LineManagerL1Pending: "WS02",
    LineManagerL2Pending: "WS03",
    InterviewScheduled: "WS04",
    pendingHODSelection: "WS05",
    CandidateSelectedIPanel: "WS06",
    CandidateOnHoldIPanel: "WS07",
    CandidateRejectedIPanel: "WS08",
    PendingRecruitmentHRscheduleInterview: "WS09",
    HRRejected: "WS10",
    HROnHold: "WS11",
    LineManagerLevel1OnHold: "WS12",
    LineManagerLevel2OnHold: "WS13",
    LineManagerLevel1Rejected: "WS14",
    LineManagerLevel2Rejected: "WS15",
    // post Recrutiment
    PendingCandidateUploadBGVDocs: "WS37",
    UploadedtheCandidateBGVDocs: "WS38",
    initiatetheBGVProcess: "WS39",
    Offerdecline: "WS25",
    SysytmeDecline: "WS26",
    // KCSA
    Pendingwithcandidatetosignofferletter: "WS16",
    CandidateuploadedtheSignedOfferLetter: "WS17",
    PendingwithCandidatetouploadotherDocuments: "WS18",
    CandidateUploadedcandidatepersonalDocs: "WS19",
    PendingwithCandidatetosignEmployementContract: "WS20",
    UploadedthesignedEmployementcontractform: "WS21",
    // Labor Hire
    PendingHROfferInitiate: "WS27",
    PendingLabourHireOfferRelease: "WS28",
    PendingLabourhireWPPayment: "WS29",
    PendingFinancePaymentReview: "WS30",
    PendingLHWorkPermitProcess: "WS31",
    PendingHREmploymentContractInit: "WS32",
    PendingLHECRelease: "WS33",
    OnboardingInprogress: "WS36",
    RevertedBacktoCandidateforreuploadofferLetter: "WS22",
    RevertedBacktoCandidateforreuploadDocs: "WS23",
    RevertedBacktoCandidateforreuploadEmploymentContract: "WS24",
    RevertedtheLabourHireOfferRelease: "WS34",
    RevertedtheLabourHireEmployementContract: "WS35",
    RevetedBacktoBGVDocuments: "WS40"
};
exports.RoleName = {
    LineManager: "Line Manager",
    RecruitmentHR: "RecruitmentHR",
    HOD: "HOD",
    EXCO: "EXCO",
    InterviewPanel: "InterviewPanel"
};
exports.TabName = {
    //HR Lead
    AssignRecuritmentHR: "Assign Recruitment HR",
    UploadONEMDoc: "Upload ONEM Doc",
    MySubmission: "My Submission",
    // Recruitment HR(PreSelection)
    UploadAdvertisement: "Job Advertisement",
    AssignAgencies: "Assign Agencies",
    UploadCV: "Upload CV",
    // Recruitment HR(PostSelection)
    ReviewProfile: "Review Profile",
    AssignInterviewPanel: "Assign Interview Panel",
    InterviewpanelL1: "Interview Panel Level-1",
    InterviewpanelL2: "Interview Panel Level-2",
    InterviewQuestion: "Interview Questions",
    // Candidate Articles
    // UploadDocuments: "Upload Documents",
    // ViewDocuments: "View Documents",
    // CandidateDocuments: "Candidate Documents",
    BackgroundVerification: "Background Verification",
    OfferLetterLabourHire: "Offer Letter - Labour Hire",
    OfferLetterKSCA: "Offer Letter - KCSA",
    // HOD
    ReviewJobAdvertisement: "Review Job Advertistment",
    ReviewScorecard: "Review Score card",
    Evaluation: "Evaluation",
    // line Manager
    // InterviewQuestions: "Interview Questions",
    CandidateDetails: "Applicants Details",
    PositionDetails: "Job Details",
    AdvertisementDetails: "Advertisement Details",
    AdvertisementViewDetails: "View Advertisement ",
    ViewCandidateDetails: "Applicants Details",
    Scorecard: "ScoreCard",
    ViewCandidateList: "Applicants List",
    ViewJustification: "View Comments",
    EvaluationTab: "Candidate Details",
    AdvertExtension: "Advert Extension",
    ReviewLevel1: "Review Profile - Level 1",
    ReviewLevel2: "Review Profile - Level 2",
    Shortlisted: "Shortlisted",
    onHold: "On Hold",
    Rejected: "Rejected",
    OnHoldRejected: "On Hold & Rejected",
    CareerPortal: "Career Portal",
    InterviewPanel: "Interview Panel",
    ViewScoreDetails: " View ScoreCard Details",
    ReschedulInterview: "Reschedule Interview",
    OnboardingChecklist: "Pre Onboarding Checklist",
    LabourHire: "Labour Hire",
    Agent: "Agent",
    CreateAdminPage: "Create Admin Page",
    EnglishAdvertisment: "English", //"Job Advertisement",
    FrenchAdvertisement: "French" //"Offre d'emploi"
};
exports.RecuritmentHRMsg = {
    HRSuccess: "Recruitment HR Assigned for the Selected Job Titles.",
    SingleHRSuccessMsg: "Recruitment HR Assigned for the Selected Job Title.",
    ONEMDocumentMsg: "Signed and Stamped ONEM Document Uploaded Successfully.",
    AdvertisementSubmitMsg: "Advertisement Document Uploaded Successfully.",
    AdvertisementReveiwMsg: "Advertisement Reviewed Successfully.",
    AgencySucess: "Agencies Assigned for the Selected Job Titles.",
    SingleAgencyMsg: "Agencies Assigned for the Selected Job Title.",
    InterviewPanalAssignedSuccessfully: "Interview Panel Assigned Successfully.",
    InterviewPanalLevel1: "Interview Panel members for Level 1 have been Assigned Successfully.",
    InterviewPanalLevel2: "Interview Panel members for Level 2 have been Assigned Successfully.",
    RescheduleSuccessMsg: "Interview Rescheduled Successfully.",
    AdvertExtendsionSuccessMsg: "Advertisement Extension Submitted Successfully.",
    ConfirmMsg: "Are you sure you want to extension the advetisement",
    ScoreCardSubmitMsg: "The Candidate has been Interviewed and Scorecard Submitted for successfully ",
    ScoreCardMsgLevel2: "The candidate has successfully completed the Level 2 interview.",
    InterviewQuestionSuccessMsg: "Interview Panel  questionnaires has been created successfully.",
    CareerportalSuccessMsg: "Career Portal questionnaires has been created successfully.",
    ProfileReviewed: "Candidate Profile for the Job Title Reviewed and Shortlisted.",
    ProfileReviewedNo: "Candidate Profile for the Job Title Reviewed and Rejected.",
    ProfileReviewedWaitingList: "Candidate Profile for the Job Title Reviewed and On - Hold.",
    HRReviewCandidate: "Candidate Profile Reviewed Successfully.",
    CandidateSelected: "Candidate Selected and send for background verification.",
    CandidateSelectedLevel2: "Candidate Level 1 Selected Successfully",
    CandidateRejected: "Candidate Rejected.",
    CandidateOnHold: "Candidate On Hold.",
    CandidateRejectedLevel2: "Candidate Level 1 Rejected Successfully",
    CandidateonholdLevel2: "Candidate Level 1 On-Hold Successfully",
    RecuritmentSubmitMsg: "Submitted Successfully.",
    ApprovedMsg: "Advertisement Reviewed Successfully. Ready for ONEM Process (Offline).",
    RecuritmentHRMsgCancel: "Are you sure want to cancel? Any unsaved changes will be lost.",
    BackMsg: "Are you sure want go back to Home Page ?",
    ValidationErrorMsg: "One or more mandatory field are missing.Please do the needful and submit again.",
    RecruitmentErrorMsg: "Please choose the Job Code to assign Recruitment HR.",
    AgenciesErrorMsg: "Please choose the Job Code to Assign Agencies.",
    PositionIDassigned: "Selected candidate has been rejected successfully.",
    InterviewScoredAlready: "The scorecard for the candidate has already been submitted.",
    InterviewScoreCommentsAlready: "The scorecard for the candidate comments has already been submitted.",
    APIErrorMsg: "Server is temporarily unavailable. Please try again later.",
    InterviewQues: "Are you sure you want to change the option? Changing this will clear your current question, and you will need to start a new one",
    AddedMsg: "Added Successfully",
    deleteMsg: "Are you sure you want to delete this Question?",
    SelectedErrorMsg: "Please Choose the Disciplines.",
    WarningMsg: "Are you sure want to Change the Disciplines? Any unsaved changes will be lost",
    ClearWarning: "Are you sure you want to close? Unsaved changes will be lost.",
    SelectedCandidateValidation: "The requested headcount for the position has already been selected.",
    QuestionAlertMsg: "Interview questions are not available. Kindly reschedule the interview date.",
    UploadMsg: "Candidate CV Upload Successfully",
    ValidationMsg: "This Candidate Already Exists",
    BGverificationMsg: "Background Verification has been initiated successfully.",
    BGReviewedMsg: "Background Verification has been completed successfully.",
    BGReviewinitBGV: "Verified the background documents and initiated the Dot's Africa verification process.",
    RevertWGDocs: "The Background Document Reverted successfully.",
    OfferLetterMsg: "The offer letter has been uploaded successfully.",
    OfferLetterinit: "The Offer Letter process has been successfully initiated to the Labour Hire.",
    ReviewLaborHireOffer: "The Labour Hire offer has been reviewed successfully and forwarded to the candidate.",
    ReviewOfferLetterMsg: "The offer letter has been reviewed successfully and initiated the WorkPermit Document ",
    RevertedOfferLetter: "The offer letter has been reverted to candidate successfully.",
    RevertLabourOffer: "The Labour Hire Offer Release has been successfully reverted",
    WorkPermitDocs: "The WorkPermit Documents has been reviewed successfully",
    WPacknowledgeUploadContract: "WorkPermit acknowledge and Employee contract Document Upload Successfully",
    RevertWorkPermitDocs: "The Work Permit Document has been successfully reverted",
    EmploymentContractMsg: "The employment contract has been uploaded successfully.",
    EmployeementInit: "The Employment Contract process has been successfully initiated to the Labour Hire",
    ReviewEmploymentContractMsg: "The Labour Hire Employment Contract has been reviewed successfully and forwarded to the candidate.",
    ReviewECMsg: "The Employement Contract Reviewed Successfully",
    ReviewOfferLetterInitEC: "The offer letter has been reviewed successfully and initiated the Employment Contract ",
    RevertedEmploymentContractMsg: "The employment contract has been reverted successfully.",
    RevertECCocs: "The Labour Hire Employment Contract has been successfully reverted",
    FinancePaymentReviewMsg: "Finance Payment Review has been completed successfully.",
    RevertedFinancePaymentMsg: "Payment Review has been reverted to LaborHire successfully..",
    ReviewOtherDocsMsg: "Candidate documents has been reviewed successfully",
    RevertOtherDocsMsg: "Candidate documents have been reverted successfully.",
    OnboardingMsg: "Onboarding has been initiated successfully.",
    NationalityErrorMsg: "Please select the Nationality filter before proceeding.",
    QuestionValiErrorMsg: "Please add at least 5 questions before proceeding.",
    COIWarningMsg: "This is the COI profile. Are you sure you're ready to proceed?",
    FormValidationMsg: "One or more required actions are missing.",
    NationalityMsgError: "Please select the any one Nationality",
    ChecklistSaveAsDraftMsg: "Your changes are saved as a draft",
    AddLabourHireSuccessMsg: "Labour Hire details added successfully.",
    UpdateLabourHireMsg: "Labour Hire details Updated successfully.",
    AddAgentSuccessMsg: "Agent details added successfully.",
    UpdateagentMsg: "Agent details Updated Successfully.",
    NoOfUserLimitMsg: "User limit reached. Kindly upgrade or extend your user limit.",
    ResetPassword: "Are you sure you want to reset the password?",
    ResetPasswordMsg: "A password reset link has been sent to your registered email. Please check your inbox to proceed.",
    duplicatedquestionMsg: "Duplicate questions are not allowed. Please modify the question and try again.",
    ReinitiateBGVProcess: "The BGV process has been re-initiated successfully.",
    ReinitiateBGVWarningMsg: "Are you sure you want to re-initiate the Criminal Check (Fingerprint Search) as part of the BGV process for this candidate?",
};
exports.HRMSAlertOptions = {
    Success: "Success",
    Confirmation: "Confirmation",
    Error: "Error",
    Warning: "Warning",
};
//# sourceMappingURL=ScorecardConfig.js.map