"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./CandidateDocumentsRepository.module.css");
var styles = {
    repository: 'repository_c5cefd2d',
    titleRow: 'titleRow_c5cefd2d',
    titleBar: 'titleBar_c5cefd2d',
    title: 'title_c5cefd2d',
    totalBadge: 'totalBadge_c5cefd2d',
    categoryList: 'categoryList_c5cefd2d',
    categoryCard: 'categoryCard_c5cefd2d',
    categoryCardOpen: 'categoryCardOpen_c5cefd2d',
    categoryHeader: 'categoryHeader_c5cefd2d',
    categoryIconWrap: 'categoryIconWrap_c5cefd2d',
    categoryMeta: 'categoryMeta_c5cefd2d',
    categoryName: 'categoryName_c5cefd2d',
    categoryCount: 'categoryCount_c5cefd2d',
    chevronBtn: 'chevronBtn_c5cefd2d',
    chevronOpen: 'chevronOpen_c5cefd2d',
    groupBody: 'groupBody_c5cefd2d',
    fadeDown: 'fadeDown_c5cefd2d',
    docGrid: 'docGrid_c5cefd2d',
    docRow: 'docRow_c5cefd2d',
    docRowActions: 'docRowActions_c5cefd2d',
    docRowIcon: 'docRowIcon_c5cefd2d',
    docRowContent: 'docRowContent_c5cefd2d',
    docRowName: 'docRowName_c5cefd2d',
    docRowMeta: 'docRowMeta_c5cefd2d',
    docActionBtn: 'docActionBtn_c5cefd2d',
    subCategoryList: 'subCategoryList_c5cefd2d',
    subDivider: 'subDivider_c5cefd2d',
    subCategory: 'subCategory_c5cefd2d',
    subCategoryHeader: 'subCategoryHeader_c5cefd2d',
    subCategoryBar: 'subCategoryBar_c5cefd2d',
    subCategoryIconWrap: 'subCategoryIconWrap_c5cefd2d',
    subCategoryMeta: 'subCategoryMeta_c5cefd2d',
    subCategoryName: 'subCategoryName_c5cefd2d',
    subCategoryCount: 'subCategoryCount_c5cefd2d',
    subChevron: 'subChevron_c5cefd2d',
    subChevronOpen: 'subChevronOpen_c5cefd2d',
    subDocGrid: 'subDocGrid_c5cefd2d',
    modalOverlay: 'modalOverlay_c5cefd2d',
    overlayFadeIn: 'overlayFadeIn_c5cefd2d',
    modalBox: 'modalBox_c5cefd2d',
    modalSlideUp: 'modalSlideUp_c5cefd2d',
    modalHeader: 'modalHeader_c5cefd2d',
    modalFileIcon: 'modalFileIcon_c5cefd2d',
    modalFileName: 'modalFileName_c5cefd2d',
    modalHeaderActions: 'modalHeaderActions_c5cefd2d',
    modalDownloadBtn: 'modalDownloadBtn_c5cefd2d',
    modalCloseBtn: 'modalCloseBtn_c5cefd2d',
    modalIframeWrap: 'modalIframeWrap_c5cefd2d',
    modalIframe: 'modalIframe_c5cefd2d'
};
exports.default = styles;
//# sourceMappingURL=CandidateDocumentsRepository.module.scss.js.map