define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment",
    "AppTitle": "Recruitment Process",
    "HomeLabel": "Home",
    "LogoutLabel": "Logout",
    "LoadingLabel": "Loading...",
    "KamoaLogo": "Kamoa Logo",
    "MainMenu": "Main Menu",
    "KamoaCopperSa": "Kamoa Copper SA",
    "CustomTheme": "Custom Theme",
    "NoDashboardMetricsAvailable": "No dashboard metrics available",
    "PleaseCheckYourPermissionsOrTryAgainLate": "Please check your permissions or try again later.",
    "DepartmentalDemand": "Departmental Demand",
    "PendingLifecycle": "Pending lifecycle",
    "Welcome": "Welcome,",
    "YouHave": "YOU HAVE",
    "UrgentAction": "URGENT ACTION",
    "ToProcess": "TO PROCESS",
    "MyTasks": "My TASKS",
    "OngoingOversights": "ONGOING OVERSIGHTS",
    "LifecycleRoadmap": "Lifecycle Roadmap",
    "OperationalSequence": "Operational Sequence",
    "Step": "Step",
    "Step1": "STEP",
    "NationalityMismatch": "Nationality Mismatch",
    "YouCannotAssignHrForDifferentNationality": "You cannot assign HR for different nationality.",
    "InterviewDateNotReached": "Interview Date Not Reached",
    "YouCanOnlyFillTheScorecardAfterTheInterv": "You can only fill the scorecard after the interview date.",
    "AlreadySubmitted": "Already Submitted",
    "TheScorecardForThisCandidateHasAlreadyBe": "The scorecard for this candidate has already been submitted.",
    "RecruitmentBacklog": "Recruitment Backlog",
    "Showing": "Showing",
    "ResultsFor": "results for",
    "RefreshTable": "Refresh table",
    "Refresh": "Refresh",
    "BackToDashboard": "Back to Dashboard",
    "VacanciesSelected": "Vacancies Selected",
    "ChooseHrMember": "Choose HR member",
    "ChooseAgencyMember": "Choose Agency member",
    "ExecuteAssignment": "Execute Assignment",
    "Close": "Close",
    "FinalizeAssignment": "Finalize Assignment",
    "SelectedVacancies": "Selected Vacancies",
    "Vacancies": "Vacancies",
    "AssigningTo": "Assigning To",
    "NoMemberSelected": "No member selected",
    "SelectAMemberToProceed": "Select a member to proceed",
    "InstructionsCommentsForStaff": "Instructions / Comments for Staff",
    "EnterSpecificInstructionsForTheAssignedH": "Enter specific instructions for the assigned HR member...",
    "Cancel": "Cancel",
    "Sending": "Sending...",
    "ConfirmSend": "Confirm & Send",
    "FirstExtensionDate": "First Extension Date",
    "SecondExtensionDate": "Second Extension Date",
    "ThirdExtensionDate": "Third Extension Date",
    "ExtensionNotAllowed": "Extension Not Allowed",
    "YouCannotExtendTheAdvertisementAsThePost": "You cannot extend the advertisement as the posting period has",
    "AdvertisementExtension": "Advertisement Extension",
    "JobTitle": "Job Title",
    "StartDate": "Start Date",
    "EndDate": "End Date",
    "Submit": "Submit",
    "NoRecordsFound": "No records found.",
    "SelectAllRows": "Select all rows",
    "SelectRow": "Select row",
    "NoRecords": "No records",
    "To": "to",
    "Of": "of",
    "Results": "results",
    "RowsPerPage": "Rows per page",
    "PreviousPage": "Previous page",
    "NextPage": "Next page",
    "PendingRecruitmentLifecycleStatus": "Pending recruitment lifecycle status",
    "ChartPages": "Chart pages",
    "Pages": "Pages",
    "NoDepartmentInRequestForPosition": "No Department in request for position",
    "ThereAreCurrentlyNoActivePositionRequest": "There are currently no active position requests for any department.",
    "Url": "url(#",
    "HrAssignment": "HR Assignment",
    "UploadOnem": "Upload ONEM",
    "AdvertUpload": "Advert Upload",
    "ReviewProfile": "Review Profile",
    "AssignInterviewPanel": "Assign Interview Panel",
    "InterviewQuestion": "Interview Question",
    "BackgroundVerification": "Background Verification",
    "OfferReleaseLabourHire": "Offer Release - Labour Hire",
    "OfferReleaseKcsa": "Offer Release - KCSA",
    "AdvertReview": "Advert Review",
    "CreateMinimumCriteriaQuestion": "Create Minimum Criteria Question",
    "PositionId": "Position ID",
    "InterviewsScheduled": "Interviews Scheduled",
    "InterviewTracking": "Interview Tracking",
    "OfferLettersReleased": "Offer Letters Released",
    "OffersAccepted": "Offers Accepted",
    "OffersRejected": "Offers Rejected",
    "CandidatesOnboarded": "Candidates Onboarded",
    "AdvertExtension": "Advert Extension",
    "AssignAgencies": "Assign Agencies",
    "MySubmission": "My Submission",
    "MySubmissionBgv": "Recruitment In Progress",
    "SubmittedSuccessfully": "Submitted Successfully",
    "RequiredFieldsMissing": "Required Fields Missing",
    "OneOrMoreFieldsAreRequiredPleaseComplete": "One or more fields are required. Please complete all highlighted fields before submitting.",
    "NoMatchingRoleFound": "No matching role found",
    "SomethingWentWrong": "Something Went Wrong",
    "AnUnexpectedErrorOccurredPleaseTryAgain": "An unexpected error occurred. Please try again.",
    "AreYouSureYouWantToCancel": "Are you sure you want to cancel?",
    "PositionStatus": "Position Status",
    "RecruitmentLifecycleRoadmap": "Recruitment Lifecycle Roadmap",
    "OnemSignedAndStampedDocumentOnlyPdf": "ONEM Signed and Stamped Document (Only PDF)",
    "DraftOnemAdvertdocFrenchOnlyPdf": "Draft ONEM AdvertDoc French (Only PDF)",
    "Done": "Done",
    "CandidateProgress": "Candidate Progress",
    "Total": "Total",
    "TrackProgressForEachCandidateThroughTheR": "Track progress for each candidate through the recruitment process",
    "Candidate": "Candidate",
    "CurrentStep": "Current Step",
    "Progress": "Progress",
    "LoadingCandidates": "Loading candidates...",
    "InProgress": "In Progress",
    "NoCandidatesAreCurrentlyScheduledForAnIn": "No candidates are currently scheduled for an interview.",
    "Previous": "Previous",
    "Page": "Page",
    "Next": "Next",
    "UnknownStatus": "Unknown Status",
    "ActiveStatus": "Active Status:",
    "UnnamedCheck": "Unnamed Check",
    "BackgroundVerificationRequirements": "Background Verification Requirements",
    "SelectTheRequiredBackgroundChecksForThis": "Select the required background checks for this job title.",
    "StandardRequirementsPreSelected": "Standard Requirements (Pre-selected)",
    "Required": "Required",
    "AdditionalRoleSpecificChecks": "Additional Role-Specific Checks",
    "VcOptionInteractive": "vc-option interactive",
    "PleaseChooseAtLeastOneBgvVerificationOpt": "Please choose at least one BGV verification option.",
    "JobAdvertisement": "Job Advertisement",
    "AdvertLanguage": "Advert Language",
    "English": "English",
    "French": "French",
    "JobDescription": "Job Description ",
    "KeyResponsibilities": "Key Responsibilities ",
    "Experience": "Experience ",
    "MinimumQualification": "Minimum Qualification ",
    "PreferredQualification": "Preferred Qualification ",
    "RoleSpecificKnowledge": "Role Specific Knowledge ",
    "RequiredLevel": "Required Level ",
    "TechnicalSkillsAbilityToApplyKnowledge": "Technical Skills - Ability to Apply Knowledge ",
    "LevelOfProficiency": "Level of Proficiency ",
    "JobFunctionalType": "Job Functional Type ",
    "PositionFramework": "Position Framework",
    "OrganizationalAlignment": "Organizational Alignment",
    "BuCode": "BU Code",
    "Department": "Department",
    "SubDepartment": "Sub Department",
    "Section": "Section",
    "DeptCode": "Dept Code",
    "AreaOfWork": "Area of Work",
    "PositionClassification": "Position Classification",
    "Nationality": "Nationality",
    "PatersonGrade": "Paterson Grade",
    "DrcGrade": "DRC Grade",
    "EmploymentCategory": "Employment Category",
    "TypeOfContract": "Type of Contract",
    "NoOfPersonS": "No of Person(s)",
    "DateRequired": "Date Required",
    "Recruitment": "Recruitment",
    "RequiredAttachments": "Required Attachments",
    "Download": "Download",
    "LoadingDocument": "Loading document...",
    "ReviewerComments": "Reviewer Comments",
    "AddYourFeedbackOrNotesHere": "Add your feedback or notes here...",
    "ReviewerCommentIsRequired": "Reviewer comment is required.",
    "IHerebyAcknowledgeThatIHaveReviewedTheJo": "I hereby acknowledge that I have reviewed the job advertisement details and attachments, and I confirm that the information is accurate and ready for publication.",
    "PleaseAcknowledgeBeforeApproving": "Please acknowledge before approving.",
    "ReviewerName": "Reviewer Name",
    "JobTitleEn": "Job Title (EN)",
    "JobTitleFr": "Job Title (FR)",
    "UploadDocuments": "Upload documents",
    "OnlyOneFileIsAllowed": "Only one file is allowed.",
    "ThisFieldIsRequired": "This field is required.",
    "UploadOneOrMoreFiles": "Upload one or more files",
    "UploadASingleFile": "Upload a single file",
    "Max": "— Max",
    "Mb": "MB",
    "ClearAll": "Clear all",
    "DropFilesHereOrClickToBrowse": "Drop files here or click to browse",
    "Accepted": "Accepted:",
    "UploadDocumentIsRequired": "Upload document is required.",
    "NoFilesSelectedYet": "No files selected yet.",
    "Remove": "Remove",
    "PleaseFixTheFollowing": "Please fix the following:",
    "Upload": "Upload",
    "UploadDocument": "Upload document",
    "ViewVacancy": "View vacancy",
    "JobCode": "Job Code",
    "JobTitleDept": "Job Title & Dept",
    "ProfileCount": "Profile Count",
    "RequestType": "Request Type",
    "ApplicantName": "Applicant Name",
    "PositionTitle": "Position Title",
    "InterviewDate": "Interview Date",
    "InterviewLevels": "Interview Levels",
    "BusinessUnit": "Business Unit",
    "LabourHire": "Labour Hire",
    "UserCode": "User Code",
    "EmailId": "Email ID",
    "View": "View",
    "ViewUser": "View user",
    "Edit": "Edit",
    "EditUser": "Edit user",
    "ManagementDashboard": "Management Dashboard",
    "NewUser": "New User",
    "LabourHireManagement": "Labour Hire Management",
    "AgencyManagement": "Agency Management",
    "PasswordReset": "Password Reset",
    "APasswordResetLinkHasBeenSentToYourEmail": "A password reset link has been sent to your email. Please check your inbox.",
    "CancelAssignment": "Cancel Assignment",
    "AreYouSureYouWantToCancelTheAssignment": "Are you sure you want to cancel the assignment?",
    "User": "User",
    "ViewingUserDetailsReadOnly": "Viewing user details — read only",
    "UpdateUserAccessAndContractDetails": "Update user access and contract details",
    "ConfigureUserAccessAndContractDetails": "Configure user access and contract details",
    "AccountStatus": "Account Status",
    "FirstName": "First Name",
    "EnterFirstName": "Enter first name",
    "LastName": "Last Name",
    "EnterLastName": "Enter last name",
    "CompanyName": "Company Name",
    "EnterLegalCompanyName": "Enter legal company name",
    "Designation": "Designation",
    "EnterRoleTitle": "Enter role / title",
    "NoOfUsers": "No. of Users",
    "TotalAllocatedSeats": "Total allocated seats",
    "StartDateOfContract": "Start Date of Contract",
    "EndDateOfContract": "End Date of Contract",
    "NewPasswordOptional": "New Password (optional)",
    "Password": "Password",
    "StringKey": "••••••••",
    "ConfirmPassword": "Confirm Password",
    "ResetPassword": "Reset Password",
    "UpdateUser": "Update User",
    "CreateEnterpriseUser": "Create Enterprise User",
    "AtLeast10CharactersLong": "At least 10 characters long",
    "ContainsAnUppercaseLetterAZ": "Contains an uppercase letter (A–Z)",
    "ContainsALowercaseLetterAZ": "Contains a lowercase letter (a–z)",
    "ContainsANumber09": "Contains a number (0–9)",
    "ContainsASpecialCharacter": "Contains a special character (!@#$…)",
    "PasswordRequirements": "Password requirements",
    "HidePassword": "Hide password",
    "ShowPassword": "Show password",
    "PendingCandidateAlert": "Pending Candidate Alert",
    "JobExpired": "Job Expired",
    "OnHold": "On Hold",
    "ProfileFrom": "Profile From",
    "ProfileReceivedDate": "Profile Received Date",
    "ReviewCandidateProfiles": "Review Candidate Profiles",
    "BelowAverage": "Below Average",
    "ClosePreview": "Close preview",
    "CandidateSelection": "Candidate selection",
    "CandidateProfileReview": "Candidate Profile Review",
    "Gender": "Gender",
    "Qualification": "Qualification",
    "MiningExp": "Mining exp.",
    "RelatedExp": "Related exp.",
    "Conflicts": "Conflicts",
    "Disability": "Disability",
    "TaxDependents": "Tax dependents",
    "CurrentPosition": "Current position",
    "GroupPartnerCompanies": "Group / partner companies",
    "Attachments": "Attachments",
    "ScreeningQuestions": "Screening Questions",
    "CandidateResponses": "Candidate responses",
    "ConflictOfInterest": "Conflict of interest",
    "ConflictOfInterestDeclared": "Conflict of Interest Declared",
    "ConsultedWith": "Consulted with",
    "Select": "Select...",
    "ProofOfDiscussion": "Proof of discussion",
    "ClickToUpload": "Click to upload",
    "PdfDocDocxPngJpg": "PDF, DOC, DOCX, PNG, JPG",
    "NoAttachment": "No attachment",
    "ReasonComments": "Reason / Comments",
    "EnterYourCommentsMax256Characters": "Enter your comments (max 256 characters)...",
    "DisabilityStatus": "Disability status",
    "Comments": "Comments",
    "HrReviewFeedback": "HR Review Feedback",
    "ReviewProfileFeedbackHr": "Review Profile Feedback - HR",
    "SelectFeedback": "Select feedback",
    "InterviewScheduleLevel1": "Interview schedule - Level 1",
    "InterviewScheduleLevel2": "Interview schedule - Level 2",
    "DoYouWishToSelectThisCandidate": "Do you wish to select this candidate?",
    "PleaseReviewTheCandidateAndProvideYourFi": "Please review the candidate and provide your final decision.",
    "YesSelect": "YES, SELECT",
    "NoReject": "NO, REJECT",
    "OnHold1": "ON HOLD",
    "DecisionJustificationComments": "Decision justification / comments",
    "ProvideYourFinalDecisionRationale": "Provide your final decision rationale...",
    "ScheduleInterview": "Schedule Interview",
    "SubmitAction": "Submit action",
    "LoadingDetails": "Loading details...",
    "Preview": "Preview",
    "ClickToPreview": "Click to preview",
    "ReadyToSubmit": "Ready to submit",
    "RemoveFile": "Remove file",
    "Answer": "Answer:",
    "InterviewPanelMembers": "Interview panel members",
    "SelectAtLeast": "Select at least",
    "PanelMembers": "panel members •",
    "Selected": "selected",
    "Date": "Date",
    "StartTime": "Start time",
    "SelectTime": "Select time",
    "EndTime": "End time",
    "LoadingEvaluationForm": "Loading evaluation form…",
    "WeCouldNotLoadAllEvaluationDataPleaseTry": "We could not load all evaluation data. Please try again.",
    "Retry": "Retry",
    "CandidateInfo": "CANDIDATE INFO",
    "ApplicantName1": "APPLICANT NAME",
    "Nationality1": "NATIONALITY",
    "Gender1": "GENDER",
    "Qualification1": "QUALIFICATION",
    "MiningExp1": "MINING EXP.",
    "RelatedExp1": "RELATED EXP.",
    "InterviewDate1": "INTERVIEW DATE",
    "Level": "LEVEL",
    "Grade": "GRADE",
    "Conflicts1": "CONFLICTS",
    "Disability1": "DISABILITY",
    "StringKey1": "👥",
    "InterviewPanel": "INTERVIEW PANEL",
    "NotAcceptable": "Not Acceptable",
    "InterviewQuestionnaires": "INTERVIEW QUESTIONNAIRES",
    "TechnicalBehavioralAssessment": "Technical & Behavioral Assessment",
    "RatingGuide": "RATING GUIDE:",
    "Excellent": "Excellent",
    "Acceptable": "Acceptable",
    "ExpectedResponseGuide": "EXPECTED RESPONSE GUIDE",
    "StringKey2": "📋",
    "PanelRating": "PANEL RATING",
    "Score": "SCORE",
    "QualificationsRelevant": "QUALIFICATIONS RELEVANT",
    "ExperienceRelevant": "EXPERIENCE RELEVANT",
    "EnergyLevel": "ENERGY LEVEL",
    "MeetsJobRequirements": "MEETS JOB REQUIREMENTS",
    "WillContributeCultureRequired": "WILL CONTRIBUTE CULTURE REQUIRED",
    "ExpatExperience": "EXPAT EXPERIENCE",
    "OtherCriteriaRecognisedByPanel": "OTHER CRITERIA RECOGNISED BY PANEL",
    "BelowAvg": "Below Avg",
    "CongoleseExperience": "CONGOLESE EXPERIENCE",
    "ScorecardDetails": "SCORECARD DETAILS",
    "CoreCompetencyAssessment15Scale": "Core Competency Assessment (1–5 Scale)",
    "Required1": "— Required",
    "FeedbackRequiredRatingsBelow3": "📝 FEEDBACK REQUIRED — RATINGS BELOW 3",
    "PleaseProvideFeedbackExplainingRatingsBe": "Please provide feedback explaining ratings below 3…",
    "ConsiderForEmployment": "CONSIDER FOR EMPLOYMENT",
    "Yes": "✅ Yes",
    "No": "✕ No",
    "OverallEvaluationFeedback": "OVERALL EVALUATION FEEDBACK",
    "EnterYourOverallEvaluationFeedbackHere": "Enter your overall evaluation feedback here…",
    "IHerebyAcknowledgeThatIHaveCompletedTheC": "I hereby acknowledge that I have completed the candidate evaluation and scorecard entry, and I confirm that the scores and feedback provided are accurate.",
    "ReviewerName1": "REVIEWER NAME",
    "JobTitleEn1": "JOB TITLE (EN)",
    "JobTitleFr1": "JOB TITLE (FR)",
    "SubmitEvaluation": "Submit Evaluation",
    "QualificationRelevant": "Qualification (Relevant)",
    "ExperienceRelevant1": "Experience (Relevant)",
    "EnergyLevel1": "Energy Level",
    "MeetsAllJobRequirements": "Meets All Job Requirements",
    "WillContributeToCultureRequired": "Will Contribute to Culture Required",
    "OtherCriteriaRecognizedByPanel": "Other Criteria Recognized by Panel",
    "LoadingData": "Loading data",
    "GoToDashboard": "Go to Dashboard",
    "Interviewer": "Interviewer",
    "Panel": "panel_",
    "ReviewScorecard": "Review Scorecard",
    "CandidateScorecardReview": "Candidate Scorecard Review",
    "OverallGpa": "OVERALL GPA",
    "Levels": "Levels",
    "QuestionEvaluationScorecard": "QUESTION EVALUATION SCORECARD",
    "PanelWiseQuestionScoresAllInterviewers": "Panel-wise Question Scores — All Interviewers",
    "OverallEvaluationScorecard": "OVERALL EVALUATION SCORECARD",
    "CoreCriteriaScoresAllInterviewersMax5Per": "Core Criteria Scores — All Interviewers (Max 5 per criterion)",
    "ViewComments": "VIEW COMMENTS",
    "Cancel1": "CANCEL",
    "Submitting": "Submitting…",
    "SubmitAction1": "SUBMIT ACTION",
    "KeyframesSpinFromTransformRotate0degToTr": "@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }",
    "Preview1": "Preview:",
    "DownloadFile": "Download file",
    "PreviewOf": "Preview of",
    "MbNbspNbsp": "MB &nbsp;·&nbsp;",
    "PreviewDocument": "Preview document",
    "DownloadDocument": "Download document",
    "DocumentsAvailable": "DOCUMENTS AVAILABLE",
    "CandidateDocumentsRepository": "CANDIDATE DOCUMENTS REPOSITORY",
    "TotalFiles": "Total Files",
    "LouisBarendVanWyk": "Louis Barend Van Wyk",
    "EvodieMushiyaKadima": "Evodie Mushiya Kadima",
    "PleaseCompleteAllHighlightedFieldsBefore": "Please complete all highlighted fields before submitting.",
    "ReinitiateBgv": "Reinitiate BGV",
    "RejectBgv": "Reject BGV",
    "ApproveBgv": "Approve BGV",
    "UnexpectedStatus": "Unexpected status",
    "BackgroundChecks": "Background Checks",
    "SignedOfferLetter": "Signed Offer Letter",
    "EmploymentContract": "Employment Contract",
    "WorkPermitApproved": "Work Permit Approved",
    "VisaProcess": "Visa Process",
    "AccommodationBooked": "Accommodation Booked",
    "TravelProcess": "Travel Process",
    "ReadyForOnboarding": "Ready for Onboarding",
    "MedicalChecks": "Medical Checks",
    "CandidateStatus": "Candidate Status",
    "CandidateLifecycleRoadmap": "Candidate Lifecycle Roadmap",
    "ViewBgvComments": "View BGV Comments",
    "ReInitiate": "Re Initiate",
    "SaveAsDraft": "Save As Draft",
    "FileConversionError": "File conversion error:",
    "NoFileUploaded": "No file uploaded",
    "PleaseUploadProofOfDiscussion": "Please upload proof of discussion.",
    "CommentsAreRequired": "Comments are required.",
    "DoYouWishToProceedWithThisAction": "Do you wish to proceed with this action ?",
    "Yes1": "Yes",
    "No1": "No",
    "ErrorReadingFile": "Error reading file:",
    "CandidateConsentForm": "Candidate Consent Form",
    "ConsentForm": "Consent Form",
    "DownloadTheFormAddYourSignatureThenUploa": "Download the form, add your signature, then upload the signed copy below.",
    "DownloadTemplate": "Download Template",
    "Kb": "KB",
    "ClickToUploadSignedForm": "Click to upload signed form",
    "PdfOrWordDocumentMax5mb": "PDF or Word document max 5MB",
    "PleaseUploadTheSignedConsentFormToProcee": "Please upload the signed consent form to proceed.",
    "ReplaceDocument": "Replace Document",
    "PersonalProtectiveEquipmentSizingInforma": "Personal Protective Equipment sizing information",
    "PpeSizingDetails": "PPE sizing details",
    "PersonalProtectiveEquipment": "Personal Protective Equipment",
    "PpeKit": "PPE Kit",
    "Size": "Size",
    "PpeSizes": "PPE sizes",
    "PrechecklistItem": "prechecklist__item",
    "Id": "ID:",
    "OnboardingPrechecklist": "Onboarding Prechecklist",
    "MandatoryPreHireChecks": "Mandatory pre-hire checks",
    "AllRequirementsMet": "All requirements met!",
    "ChecklistInProgress": "Checklist in progress",
    "YouCanNowSubmitThisCandidateForReview": "You can now submit this candidate for review.",
    "CompleteAllItemsAboveToEnableSubmission": "Complete all items above to enable submission.",
    "ClickToUploadWorkPermitAcknowledgement": "Click to upload Work Permit Acknowledgement",
    "PdfOrWordDocumentMax5Mb": "PDF or Word document · max 5 MB",
    "WorkPermitAcknowledgement": "Work Permit Acknowledgement",
    "UploadTheSignedAcknowledgementDocument": "Upload the signed acknowledgement document",
    "PleaseUploadTheWorkPermitAcknowledgement": "Please upload the Work Permit Acknowledgement document.",
    "DocumentVerificationStatus": "Document Verification Status",
    "Verified": "Verified",
    "Rejected": "Rejected",
    "PleaseVerifyTheDocumentStatusBeforeProce": "Please verify the document status before proceeding.",
    "ContSuitPants": "Cont. Suit Pants",
    "ContSuitTop": "Cont. Suit Top",
    "SafetyShoes": "Safety Shoes",
    "ProofOfIdentity": "Proof Of Identity",
    "IdentityNumber": "Identity Number",
    "Email": "Email",
    "Location": "Location",
    "BusinessUnitCode": "Business Unit Code",
    "DepartmentCode": "Department Code",
    "JoiningDate": "Joining Date",
    "NoticePeriod": "Notice Period",
    "ReferenceEmployerDetails": "Reference Employer Details",
    "ReferenceName": "Reference Name",
    "ReferenceDesignation": "Reference Designation",
    "ReferenceEmailId": "Reference Email ID",
    "ReferenceContactNumber": "Reference Contact Number",
    "ReferenceCompanyName": "Reference Company Name",
    "MinimumRequirement": "Minimum Requirement",
    "PleaseAddAtLeast": "Please add at least",
    "FailedToSaveQuestionsPleaseTryAgain": "Failed to save questions. Please try again.",
    "GoBack": "Go back",
    "PreparedCriteria": "Prepared Criteria",
    "InterviewSet": "Interview Set",
    "Questions": "Questions",
    "FinalizeSave": "Finalize & Save",
    "QuestionSetupConfiguration": "Question Setup Configuration",
    "WhichTypeOfQuestionYouArePlanningToSetFo": "Which type of question you are planning to set for this job title?",
    "FromQuestionBank": "From Question bank",
    "SelectPreVerifiedQuestionsFromOurOfficia": "Select pre-verified questions from our official library",
    "CreateNewSetOfQuestion": "Create New set of question",
    "AuthorCustomQuestionsSpecificallyForThis": "Author custom questions specifically for this role",
    "CombineLibraryTemplatesWithCustomAuthore": "Combine library templates with custom authored questions",
    "CancelProcess": "Cancel Process",
    "CreateMinimumCriteria": "Create Minimum Criteria",
    "SingleChoice": "Single Choice",
    "MultipleChoice": "Multiple Choice",
    "EnglishQuestion": "English Question",
    "EnterQuestionInEnglish": "Enter question in English...",
    "FrenchQuestion": "French Question",
    "SaisirLaQuestionEnFranAis": "Saisir la question en français...",
    "AnswerOptions": "Answer Options",
    "AddOption": "Add Option",
    "OptionEnglish": "Option (English)",
    "OptionFranAis": "Option (Français)",
    "RemoveOption": "Remove option",
    "ClearAll1": "Clear All",
    "AddToCriteriaSet": "Add to Criteria Set",
    "PreparedMinimumCriteria": "Prepared Minimum Criteria",
    "Items": "Items",
    "NoCriteriaAddedYet": "No criteria added yet",
    "SelectFromBankOrCreateNew": "Select from bank or create new",
    "FromBank": "From Bank",
    "FranAis": "Français",
    "QuestionBank": "Question Bank",
    "Templates": "Templates",
    "NoQuestionsFound": "No questions found",
    "AlreadyAdded": "Already added",
    "AddToCriteria": "Add to criteria",
    "CreateNewQuestion": "Create New Question",
    "DraftCustomBilingualContent": "Draft custom bilingual content",
    "AddToInterviewSet": "Add to Interview Set",
    "En": "EN",
    "EnglishVersion": "English Version",
    "QuestionPrompt": "Question Prompt",
    "EnterTheQuestionInEnglish": "Enter the question in English...",
    "ExpectedAnswer": "Expected Answer",
    "WhatAreTheKeyPointsForAGoodAnswer": "What are the key points for a good answer?",
    "Fr": "FR",
    "VersionFranAise": "Version Française",
    "PromptDeLaQuestion": "Prompt de la Question",
    "SaisissezLaQuestionEnFranAis": "Saisissez la question en français...",
    "RPonseAttendue": "Réponse Attendue",
    "QuelsSontLesPointsClSDUneBonneRPonse": "Quels sont les points clés d'une bonne réponse ?",
    "PreparedInterviewSet": "Prepared Interview Set",
    "ReviewAndOrganizeYourSelectedQuestions": "Review and organize your selected questions",
    "QuestionsSelected": "Questions Selected",
    "NoQuestionsAddedToTheSetYet": "No questions added to the set yet",
    "AddFromTheLibraryOrCreateACustomOneAbove": "Add from the library or create a custom one above",
    "LibraryAsset": "Library Asset",
    "CustomDraft": "Custom Draft",
    "ReuseStandardQuestions": "Reuse Standard Questions",
    "NoTemplatesAvailable": "No templates available",
    "NbspNbspStandardTemplate": "&nbsp;&nbsp;Standard Template",
    "AddToInterviewSet1": "Add to interview set",
    "ConfirmSubmission": "Confirm Submission",
    "AreYouSureYouWantToSubmitTheScorecard": "Are you sure you want to submit the scorecard?",
    "YesSubmit": "Yes, Submit",
    "AreYouSureYouWantToLeave": "Are you sure you want to leave?",
    "AnyUnsavedChangesWillBeLostDoYouWishToCo": "Any unsaved changes will be lost. Do you wish to continue?",
    "YesLeave": "Yes, Leave",
    "StayHere": "Stay Here",
    "PleaseFillAllMandatoryFields": "Please Fill All Mandatory Fields",
    "CompleteTheFollowingFieldsBeforeSubmitti": "Complete the following fields before submitting:",
    "GotIt": "Got it",
    "SubmittedSuccessfully1": "Submitted Successfully!",
    "KeyframesPulseDot0100TransformScale1Opac": "@keyframes pulse-dot { 0%, 100% { transform: scale(1); opacity: 0.5; } 50% { transform: scale(1.5); opacity: 1; } }",
    "Level1Of1Level2Of2": "Level 1 of 1 & Level 2 of 2",
    "Level1Of1": "Level 1 of 1",
    "InterviewLevel": "Interview Level",
    "ReviewScorecardProfiles": "Review Scorecard Profiles",
    "FeedbackLevel2": "Feedback — Level 2",
    "FeedbackLevel1": "Feedback — Level 1",
    "AsHodReviewTheEvaluationAndProvideYourDe": "As HOD, review the evaluation and provide your decision.",
    "PleaseSelectADecision": "⚠ Please select a decision.",
    "AssignPositionId": "Assign Position ID",
    "SelectAPosition": "Select a position…",
    "NoPositionsAvailable": "No positions available.",
    "ExpatExp": "EXPAT EXP.",
    "PanelAssessmentResults": "Panel Assessment Results",
    "LoadingQuestions": "Loading questions…",
    "NoQuestionsFoundForThisJob": "No questions found for this job.",
    "ExpectedAnswer1": "Expected Answer:",
    "Rating": "RATING:",
    "PanelRecommendation": "PANEL RECOMMENDATION",
    "ConsiderForEmployment1": "✓ Consider for Employment",
    "DoNotConsider": "✕ Do Not Consider",
    "NoDataAvailable": "No data available.",
    "Criteria": "Criteria"
  }
});
